# Generated by Django 4.2.20 on 2025-04-26 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzaRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='evaluation_photos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quality_percentage', models.FloatField()),
                ('crust_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzeriaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stream_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_quantity', models.IntegerField()),
                ('expected_quantity', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_evaluations', to='evaluateRegister.evaluation')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaRegister.ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluateRegister.pizzerialocation'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaRegister.pizzas'),
        ),
    ]
