# Generated by Django 4.2.20 on 2025-05-23 12:56

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('pizza_size', models.FloatField()),
                ('crust_size', models.FloatField()),
            ],
            options={
                'db_table': 'pizzas',
            },
        ),
        migrations.CreateModel(
            name='PizzaEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pizza_images/')),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True)),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaRegister.pizzas')),
            ],
            options={
                'db_table': 'pizza_embeddings',
            },
        ),
        migrations.CreateModel(
            name='PizzaComposition',
            fields=[
                ('pizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pizzaRegister.pizzas')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizzaRegister.ingredients')),
            ],
            options={
                'db_table': 'pizza_composition',
                'unique_together': {('pizza', 'ingredient')},
            },
        ),
    ]
